
{% set data = load_setup_py_data() %}


package:
    name    : rixcalc

    version : {{ data.get('version') }}


source:
    path: ..

build:
    number: 1
    noarch: python

requirements:
    build:
      - python >=3.9
      - setuptools

    run:
      - python >=3.9

test:
    imports:
      - rixcalc

    requires:
      - pytest

about:
  home: https://github.com/pcdshub/rixcalc
  license: SLAC Open License
  summary: General Purpose IOC for using python to calculate and build various PVs for RIX hutch
